name: RobertRhodesVO
favicon: null
layout_spectrum: 0.50175
typography_spectrum: 0.521382
title: Robert Hollywood Rhodes
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#07040b'
    - '#edcede'
    - '#faf6f7'
    - '#544b60'
    - '#826b87'
  brandStrength: 0.9375
  lightness: 0.0625
  saturation: 0.5625
  rhythmicContrast: 1
purpose: []
