analytics: {}
color:
  brandColors:
    - '#040402'
    - '#74ffff'
    - '#f1fffe'
    - '#316925'
    - '#35b2dd'
  brandStrength: 0.9375
  lightness: 0.0625
  rhythmicContrast: 1
  saturation: 0.5625
cta: {}
layout_spectrum: 0.225329
name: RobertRhodesVO
opengraph: {}
purpose: []
title: VoiceOver
typography_spectrum: 0.521382
