name: RobertRhodesVO
favicon: null
layout_spectrum: 0.50175
typography_spectrum: 0.84643
title: Robert Hollywood Rhodes
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#f80000'
    - '#fefefe'
    - '#464646'
    - '#868686'
  brandStrength: 0.9375
  lightness: 0.0625
  saturation: 0.5
  rhythmicContrast: 1
purpose: []
