name: RobertRhodesVO
favicon: null
layout_spectrum: 1
typography_spectrum: 0.87883
title: Robert Rhodes VO
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#f80000'
    - '#fefefe'
    - '#464646'
    - '#868686'
  brandStrength: 0.911712464177981
  lightness: 0.1576054934412241
  saturation: 0.6485380136873573
  rhythmicContrast: 0.0221720973495394
purpose: []
