name: RobertRhodesVO
favicon: null
layout_spectrum: 0.33627
typography_spectrum: 1
title: Robert Rhodes VO
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#f80000'
    - '#fefefe'
    - '#464646'
    - '#868686'
  brandStrength: 0.5
  lightness: 0.125
  saturation: 0.75
  rhythmicContrast: 0.75
purpose: []
