typography_spectrum: 0.2051757523462656
content_rating:
  adult: false
color:
  brandColors:
    - '#080413'
    - '#2923ff'
    - '#58bafc'
    - '#05fefd'
    - '#97fffd'
  brandStrength: 0.7639570067691073
  lightness: 0.20894307776003856
  saturation: 0.36292454726330126
  rhythmicContrast: 0.22480172104700147
github: true
opengraph:
  type: ''
  appId: ''
  image: >-
    https://the-grid-user-content.s3-us-west-2.amazonaws.com/2879aaa3-011e-4056-b5ec-54fed2d1e9d4.jpg
layout_spectrum: 0.9468285917485187
analytics: {}
author:
  name: 'RJR Productions Inc '
  email: robertrhodesvo@gmail.com
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/b7b3b8ac-1edf-4df4-8e9d-2a5ec6b40fa4.png
name: RobertRhodesVO
cta: {}
navigation:
  - name: About Robert "Hollywood"?
    id: 81ae859b-9cb6-45ea-ac58-db2c521d2a8b
    type: content
  - name: Voice Reel
    id: 1f350a0e-861a-422e-bf19-b171878376ec
    type: content
  - name: My Latest Credits
    id: c11c0c5b-78ea-422c-8e7b-7e77cee6a2d2
    type: content
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/1db21d04-223f-4a24-9487-69d26b0e1897.jpg
title: Robert Rhodes Voiceovers
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/48ac2248-4030-4e6c-9e42-f62eaeed74ee.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/48ac2248-4030-4e6c-9e42-f62eaeed74ee.jpg
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      keywords: []
      description: ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/0843510f-91e2-4417-be0d-2f4b455bcd63.png">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/0843510f-91e2-4417-be0d-2f4b455bcd63.png
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      keywords: []
      description: ''
      inLanguage: !<tag:yaml.org,2002:js/undefined> ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
description: ''
purpose:
  - type: contact
    label: Book A Session
    url: 'mailto:robertrhodesvo@gmail.com'
  - type: external
    label: Reel and Representation
    url: 'http://hollywood.voicezam.com/?m=5461'
