name: RobertRhodesVO
favicon: null
layout_spectrum: 0.799342
typography_spectrum: 0.521382
title: VoiceOver
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#040402'
    - '#74ffff'
    - '#f1fffe'
    - '#316925'
    - '#35b2dd'
  brandStrength: 0.9375
  lightness: 0.0625
  saturation: 0.5625
  rhythmicContrast: 1
purpose: []
