typography_spectrum: 0.2051757523462656
content_rating:
  adult: false
color:
  brandColors:
    - '#080413'
    - '#2923ff'
    - '#58bafc'
    - '#05fefd'
    - '#97fffd'
  brandStrength: 0.7639570067691073
  lightness: 0.20894307776003856
  saturation: 0.36292454726330126
  rhythmicContrast: 0.22480172104700147
github: true
opengraph:
  type: ''
  appId: ''
  image: >-
    https://the-grid-user-content.s3-us-west-2.amazonaws.com/2879aaa3-011e-4056-b5ec-54fed2d1e9d4.jpg
layout_spectrum: 0.9468285917485187
analytics: {}
author:
  name: 'RJR Productions Inc '
  email: robertrhodesvo@gmail.com
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/b7b3b8ac-1edf-4df4-8e9d-2a5ec6b40fa4.png
name: RobertRhodesVO
cta: {}
navigation:
  - name: About Robert "Hollywood"?
    id: 81ae859b-9cb6-45ea-ac58-db2c521d2a8b
    type: content
  - name: Voice Reel
    id: 1f350a0e-861a-422e-bf19-b171878376ec
    type: content
  - name: My Latest Credits
    id: c11c0c5b-78ea-422c-8e7b-7e77cee6a2d2
    type: content
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/1db21d04-223f-4a24-9487-69d26b0e1897.jpg
title: Robert Rhodes Voiceovers
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: video
    html: >-
      <iframe
      src="https://cdn.embedly.com/widgets/media.html?src=https%3A%2F%2Fwww.youtube.com%2Fembed%2FyUl0PwycBX0%3Ffeature%3Doembed&url=http%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DyUl0PwycBX0&image=https%3A%2F%2Fi.ytimg.com%2Fvi%2FyUl0PwycBX0%2Fhqdefault.jpg&key=a715cf41cc93453ca338d350cd26f87b&type=text%2Fhtml&schema=youtube"
      width="640" height="360" scrolling="no" frameborder="0"
      allowfullscreen></iframe>
    src: !<tag:yaml.org,2002:js/undefined> ''
    metadata:
      author:
        - name: Hollywood Rhodes
          url: 'https://www.youtube.com/channel/UC-iJiwt7X_ijrp8Vg_rVCfA'
          avatar: {}
      related: []
      publisher:
        url: 'https://www.youtube.com/'
        name: YouTube
        favicon: 'https://s.ytimg.com/yts/img/favicon-vflz7uhzw.ico'
        domain: youtu.be
      keywords:
        - ''
      description: Uploaded by Hollywood Rhodes on 2017-08-21.
      '@type': VideoObject
      app_links:
        - url: 'vnd.youtube://www.youtube.com/watch?v=yUl0PwycBX0&feature=applinks'
          type: ios
          namespace: ai
          app_store_id: '544007664'
          app_name: YouTube
        - url: 'vnd.youtube://www.youtube.com/watch?v=yUl0PwycBX0&feature=applinks'
          type: android
          namespace: ai
          app_name: YouTube
          package: com.google.android.youtube
        - url: 'https://www.youtube.com/watch?v=yUl0PwycBX0&feature=applinks'
          type: web
          namespace: ai
        - url: 'vnd.youtube://www.youtube.com/watch?v=yUl0PwycBX0&feature=applinks'
          namespace: twitter
          type: ipad
          name: YouTube
          id: '544007664'
        - url: 'vnd.youtube://www.youtube.com/watch?v=yUl0PwycBX0&feature=applinks'
          namespace: twitter
          type: iphone
          name: YouTube
          id: '544007664'
        - url: 'https://www.youtube.com/watch?v=yUl0PwycBX0'
          namespace: twitter
          type: googleplay
          name: YouTube
          id: com.google.android.youtube
        - path: http/www.youtube.com/watch?v=yUl0PwycBX0
          package: com.google.android.youtube
          namespace: google
          type: android
        - path: vnd.youtube/www.youtube.com/watch?v=yUl0PwycBX0
          package: '544007664'
          namespace: google
          type: ios
      '@context': 'http://schema.org'
      isBasedOnUrl: 'https://youtu.be/yUl0PwycBX0'
      title: RR Background 082017
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/7814f62a-1266-439c-b273-b0bfdb321d31.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/7814f62a-1266-439c-b273-b0bfdb321d31.jpg
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      keywords: []
      description: ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/a251cc7e-1d6a-40c4-9402-2f1052428f82.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/a251cc7e-1d6a-40c4-9402-2f1052428f82.jpg
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      keywords: []
      description: ''
      inLanguage: !<tag:yaml.org,2002:js/undefined> ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
description: ''
purpose:
  - type: contact
    label: Book A Session
    url: 'mailto:robertrhodesvo@gmail.com'
  - type: external
    label: Reel and Representation
    url: 'http://hollywood.voicezam.com/?m=5461'
