name: RobertRhodesVO
favicon: null
layout_spectrum: 1
typography_spectrum: 0.43451
title: Robert Rhodes VO
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0c091a'
    - '#542bb7'
    - '#a81ee6'
    - '#a27bf8'
    - '#d0aaff'
  brandStrength: 0.9375
  lightness: 0.375
  saturation: 0.6875
  rhythmicContrast: 0.75
purpose: []
