name: RobertRhodesVO
favicon: null
layout_spectrum: 0.50175
typography_spectrum: 0.84643
title: Robert Hollywood Rhodes
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#010101'
    - '#fcfcfc'
    - '#555555'
    - '#969696'
    - '#e6b705'
  brandStrength: 0.9375
  lightness: 0.0625
  saturation: 0.5
  rhythmicContrast: 1
purpose: []
