typography_spectrum: 0.2051757523462656
content_rating:
  adult: false
color:
  brandColors:
    - '#080413'
    - '#2923ff'
    - '#58bafc'
    - '#05fefd'
    - '#97fffd'
  brandStrength: 0.7639570067691073
  lightness: 0.20894307776003856
  saturation: 0.36292454726330126
  rhythmicContrast: 0.22480172104700147
github: true
opengraph:
  type: ''
  appId: ''
  image: >-
    https://the-grid-user-content.s3-us-west-2.amazonaws.com/ca5a12d4-b3de-4710-8b2a-d399253b4397.jpg
layout_spectrum: 0.9468285917485187
analytics: {}
author:
  email: robertrhodesvo@gmail.com
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/b7b3b8ac-1edf-4df4-8e9d-2a5ec6b40fa4.png
name: RobertRhodesVO
url: 'https://robertrhodesvo.com'
cta: {}
navigation:
  - name: About ME
    id: 81ae859b-9cb6-45ea-ac58-db2c521d2a8b
    type: content
favicon: null
title: Robert Rhodes Voiceover
content: []
description: SAG/AFTRA
purpose:
  - type: contact
    label: Book A Session
    url: 'mailto:robertrhodesvo@gmail.com'
  - type: external
    label: Reel and Representation
    url: 'http://hollywood.voicezam.com/?m=5461'
