name: RobertRhodesVO
favicon: null
layout_spectrum: 0.26508
typography_spectrum: 0.84643
title: Robert Hollywood Rhodes
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#080413'
    - '#2923ff'
    - '#58bafc'
    - '#05fefd'
    - '#97fffd'
  brandStrength: 0.9375
  lightness: 0.0625
  saturation: 0.5
  rhythmicContrast: 1
purpose: []
