name: RobertRhodesVO
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/acd6ce69-8dd2-4245-8640-0c4ab01b113d.jpg
layout_spectrum: 0.26508
typography_spectrum: 0.84643
cta: {}
analytics: {}
opengraph:
  type: ''
  appId: ''
color:
  brandColors:
    - '#080413'
    - '#2923ff'
    - '#58bafc'
    - '#05fefd'
    - '#97fffd'
  brandStrength: 0.9375
  lightness: 0.0625
  saturation: 0.5
  rhythmicContrast: 1
purpose:
  - type: contact
    url: 'mailto:robertrhodesvo@gmail.com'
    label: Booking
title: Voice Talent SAG/AFTRA
description: Robert Rhodes
author:
  name: ''
  url: ''
  email: robertrhodesvo@gmail.com
content_rating:
  adult: false
navigation:
  - name: About ME
    id: 81ae859b-9cb6-45ea-ac58-db2c521d2a8b
    type: content
github: true
