typography_spectrum: 0.9626273111637571
content_rating:
  adult: false
color:
  brandColors:
    - '#080413'
    - '#2923ff'
    - '#58bafc'
    - '#05fefd'
    - '#97fffd'
  brandStrength: 0.5321622673179586
  lightness: 0.5904145533104639
  saturation: 0.8078361017541905
  rhythmicContrast: 0.9201950991307708
github: true
opengraph:
  type: ''
  appId: ''
layout_spectrum: 0.9209878797083172
analytics: {}
author:
  name: ''
  url: ''
  email: robertrhodesvo@gmail.com
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/acd6ce69-8dd2-4245-8640-0c4ab01b113d.jpg
name: RobertRhodesVO
cta: {}
navigation:
  - name: About ME
    id: 81ae859b-9cb6-45ea-ac58-db2c521d2a8b
    type: content
title: SAG/AFTRA
content: []
description: SAG/AFTRA
purpose:
  - type: contact
    url: 'mailto:robertrhodesvo@gmail.com'
    label: Booking
